apiVersion: apps/v1
kind: Deployment
metadata:
  name: matricula-deployment
  labels:
    app: matricula-deployment
spec:
  selector:
    matchLabels:
      app: matricula-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: matricula-deployment
    spec:
      containers:
        - name: tingeso-matricula-service
          image: perrosky/tingeso-matricula-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_MATRICULA
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_MATRICULA
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: matricula-service
  labels:
    app: matricula-service
spec:
  selector:
    app: matricula-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer