apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB_ESTUDIANTE: tingesoestudiante
  POSTGRES_DB_ARANCEL: tingesoarancel
  POSTGRES_DB_MATRICULA: tingesomatricula
  POSTGRES_DB_CUOTA: tingesocuota
